FROM openjdk:8u222-jdk-slim-buster AS builder

ENV CONDA_DIR="/opt/conda"
ENV SPARK_HOME="/opt/spark"
ENV PATH="$CONDA_DIR/bin:$SPARK_HOME/bin:$PATH"

# Install conda
RUN apt-get update -y  --fix-missing && apt-get -y install curl git bash wget tini dnsutils iputils-ping ca-certificates  libglib2.0-0 libxext6 libsm6 libxrender1 && \
    apt-get clean && \
    \
    mkdir -p "$CONDA_DIR" && \
    curl "https://repo.continuum.io/miniconda/Miniconda3-4.7.10-Linux-x86_64.sh"  -o miniconda.sh  && \
    bash miniconda.sh -f -b -p "$CONDA_DIR" && \
    echo "export PATH=$CONDA_DIR/bin:\$PATH" > /etc/profile.d/conda.sh && \
    rm miniconda.sh && \
    \
    conda update --all --yes && \
    conda clean -afy && \
    #install spark
    curl -O https://archive.apache.org/dist/spark/spark-2.4.3/spark-2.4.3-bin-hadoop2.7.tgz && \
    tar -xzf spark-2.4.3-bin-hadoop2.7.tgz && \
    mv spark-2.4.3-bin-hadoop2.7  $SPARK_HOME && \
    rm  spark-2.4.3-bin-hadoop2.7.tgz
 